In [1]:
import pandas as pd

df= pd.read_csv("orders.csv")

In [6]:
df.columns

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='str')

In [7]:
df.index

RangeIndex(start=0, stop=40, step=1)

In [11]:
len(df["Country"])

40

In [ ]:
set(df["Category"])

{'Electronics', 'Furniture', 'Stationery'}

In [17]:
df[["Country", "Product", "Category"]]

         Country                Product     Category
0            USA                 Laptop  Electronics
1         Canada             Headphones  Electronics
2            UAE           Office Chair    Furniture
3      Singapore              Desk Lamp    Furniture
4         Mexico               Keyboard  Electronics
5            UAE               Notebook   Stationery
6             UK          Standing Desk    Furniture
7    South Korea                Monitor  Electronics
8          Italy                    Pen   Stationery
9          Japan                  Mouse  Electronics
10        France                 Webcam  Electronics
11         India           File Cabinet    Furniture
12     Australia                Stapler   Stationery
13         Spain              USB Drive  Electronics
14         China              Bookshelf    Furniture
15         Egypt          Printer Paper   Stationery
16        Poland         Wireless Mouse  Electronics
17           USA         Desk Organizer    Furniture
18         Japan             Calculator  Electronics
19  Saudi Arabia             Whiteboard    Furniture
20        Canada           Highlighters   Stationery
21        Brazil      Bluetooth Speaker  Electronics
22       Germany           Office Plant    Furniture
23      Pakistan           Sticky Notes   Stationery
24        Sweden           Tablet Stand  Electronics
25        France         Paper Shredder  Electronics
26     Argentina         Desk Chair Mat    Furniture
27        Russia           Binder Clips   Stationery
28   South Korea      Wireless Keyboard  Electronics
29         Italy          Desk Calendar    Furniture
30       Morocco                USB Hub  Electronics
31       Germany       Document Scanner  Electronics
32      Colombia  Desk Drawer Organizer    Furniture
33           USA            Index Cards   Stationery
34         Japan          Monitor Stand  Electronics
35            UK     Desk Lamp with USB    Furniture
36      Portugal       Wireless Earbuds  Electronics
37          Iran               Desk Pad    Furniture
38   South Korea            Power Strip  Electronics
39       Ukraine             Desk Clock    Furniture

In [18]:
df.iloc[5]

OrderID                 1006
CustomerName    Nora Ibrahim
Product             Notebook
Category          Stationery
Quantity                   5
Price                    5.0
OrderDate         2024-06-07
Shipped                  Yes
Country                  UAE
Name: 5, dtype: object

In [19]:
df.head(2)

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada

In [24]:
df[(df["Category"] == "Electronics") & (df["Country"] == "USA")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA

In [25]:
df[(df["Category"] == "Electronics") | (df["Country"] == "USA")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea

In [28]:
df[(df["Quantity"] > 5) & (df["Quantity"] <20)]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia

In [29]:
df[df["Country"].isin(["USA", "Brazil", "Germany"])]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [33]:
df.loc[df["CustomerName"] == "Anna Ivanova", "Product"] = "Another Product"

In [34]:
df.loc[df["CustomerName"] == "Anna Ivanova"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
39,1040,Anna Ivanova,Another Product,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [41]:
df.loc[df["Country"] == "United States", "Country"] = "USA"

In [42]:
df.loc[df["Country"] == "USA"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [43]:
df["Country"] = df["Country"].str.upper()

In [44]:
df["Country"]

0              USA
1           CANADA
2              UAE
3        SINGAPORE
4           MEXICO
5              UAE
6               UK
7      SOUTH KOREA
8            ITALY
9            JAPAN
10          FRANCE
11           INDIA
12       AUSTRALIA
13           SPAIN
14           CHINA
15           EGYPT
16          POLAND
17             USA
18           JAPAN
19    SAUDI ARABIA
20          CANADA
21          BRAZIL
22         GERMANY
23        PAKISTAN
24          SWEDEN
25          FRANCE
26       ARGENTINA
27          RUSSIA
28     SOUTH KOREA
29           ITALY
30         MOROCCO
31         GERMANY
32        COLOMBIA
33             USA
34           JAPAN
35              UK
36        PORTUGAL
37            IRAN
38     SOUTH KOREA
39         UKRAINE
Name: Country, dtype: str

In [48]:
df["Category"].value_counts()

Category
Electronics    18
Furniture      14
Stationery      8
Name: count, dtype: int64

In [49]:
df.groupby("Country")["Price"].sum()

Country
ARGENTINA         22.0
AUSTRALIA         12.0
BRAZIL            95.0
CANADA           153.5
CHINA            280.0
COLOMBIA          42.0
EGYPT              8.0
FRANCE           160.0
GERMANY          175.0
INDIA            180.0
IRAN              28.0
ITALY             19.5
JAPAN            105.0
MEXICO            80.0
MOROCCO           32.0
PAKISTAN           4.0
POLAND            45.0
PORTUGAL         125.0
RUSSIA             2.5
SAUDI ARABIA     120.0
SINGAPORE         45.0
SOUTH KOREA      348.0
SPAIN             25.0
SWEDEN            28.0
UAE              305.0
UK               518.0
UKRAINE           35.0
USA             1265.8
Name: Price, dtype: float64

In [51]:
df.to_csv("newFile.csv", index = True)